global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pixcore-api'
    static_configs:
      - targets: ['host.docker.internal:5000']
  
  - job_name: 'pixcore-worker'
    static_configs:
      - targets: ['host.docker.internal:5001']